version: '3.8'


services:
  app:
    container_name: app
    build: ./
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db
      - migrate
    networks:
      - app_network
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    


  db:
    image: postgres:15
    environment:
    - POSTGRES_DB=library
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    container_name: postgres
    env_file:
      - .env
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    container_name: migrate
    command: ["up"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

volumes:
  db_postgres:

networks:
  app_network:
    driver: bridge